name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-activity@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: keskimaki/exercise_3.1:latest
